# Analysis

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from quickrules.data_handling import calculate_score, count_all_rules
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, accuracy_score
import pandas as pd

In [11]:
data_sets = [
    'australian',  # temp disable because of mismatched labels in pred and true
    'cleveland',
    'glass',
    'heart',
    'ionosphere',
    'pima',
    'wine',
    'bupa',
    'saheart',
    'wisconsin',
    'crx',
    'ecoli',
    'haberman',
    'mammographic'
             ]

In [4]:
models = {
    'naive-bayes': 'NB-results',
    'qr-single': 'close-min-max-results',
    'qr': 'close-min-max-combo-results',
    'lin-owa': 'rules-lin-owa-qr-combo-minmax-results',
    'trun-lin-owa': 'rules-trun-lin-owa-qr-combo-minmax-results',
    'trun-exp-owa': 'trun-exp-owa-qr-combo-minmax-results',
    'prune-qr': 'prune-qr-combo-minmax-results',
    'prune-lin-owa': 'prune-lin-owa-qr-combo-minmax-results',
    'prune-trun-lin-owa': 'prune-trun-lin-owa-qr-combo-min-max-results',
    'prune-trun-exp-owa': 'prune-trun-exp-owa-qr-combo-min-max-results',
}

In [12]:
data_base = Path.cwd() / 'keel-data'
results_base = Path.cwd()
metric = balanced_accuracy_score
scores = {}
rules = {}

for model, path in models.items():
    scores[model] = calculate_score(
        data_folder=data_base,
        results_folder=results_base / path,
        include=data_sets,
        metric=metric
    )
    if model != 'naive-bayes':
        rules[model] = count_all_rules(
            Path.cwd() / results_base / path,
            include=data_sets
        )

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Unsuccessful for fold3 on australian.
Unsuccessful for fold9 on australian.

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Unsuccessful for fold1 on mammographic.
Unsuccessful for fold2 on mammographic.
Unsuccessful for fold3 on mammographic.
Unsuccessful for fold4 on mammographic.
Unsuccessful for fold5 on mammographic.
Unsuccessful for fold6 on mammographic.
Unsuccessful for fold7 on mammographic.
Unsuccessful for fold8 on mammographic.
Unsuccessful for fold9 on mammographic.
Unsuccessful for fold10 on mammographic.

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

In [26]:
df = pd.DataFrame(index=data_sets, columns=scores.keys())

In [27]:
for model, score_dict in scores.items():
    for data_set, score in score_dict.items():
        df.loc[data_set, model] = score

In [28]:
df

,naive-bayes,qr-single,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa
australian,0.777763,0.504006,0.865348,0.856859,0.860529,0.863444,0.863735,0.858174,0.860529,0.863444
cleveland,0.327258,0.212451,0.208347,0.286954,0.289811,0.282134,0.208347,0.286954,0.289811,0.286134
glass,0.487282,0.175556,0.31381,0.255853,0.283234,0.286607,0.273512,0.255853,0.267262,0.256944
heart,0.849167,0.568333,0.785833,0.785,0.786667,0.790833,0.785833,0.789167,0.786667,0.786667
ionosphere,0.861631,0.5,0.658974,0.651282,0.651282,0.651282,0.655449,0.651282,0.651282,0.651282
pima,0.722447,0.487682,0.502775,0.504698,0.502775,0.502775,0.502775,0.504698,0.504627,0.502775
wine,0.975198,0.333333,0.915873,0.796825,0.793175,0.806508,0.730952,0.796825,0.792063,0.792063
bupa,0.572695,0.5,0.5,0.4975,0.4975,0.5,0.5,0.4975,0.4975,0.5
saheart,0.671337,0.503958,0.5,0.501458,0.498333,0.498333,0.5,0.501458,0.501458,0.501458
wisconsin,0.963272,0.525556,0.933215,0.950417,0.954584,0.952501,0.952001,0.948334,0.958751,0.959912
crx,0.67995,0.5,0.501797,0.505741,0.507473,0.505688,0.501797,0.505741,0.505688,0.505688
ecoli,0.413704,0.17381,0.17585,0.247619,0.17381,0.17381,0.17381,0.247619,0.17381,0.17381
haberman,0.572527,0.5,0.5,0.50625,0.50625,0.50625,0.503706,0.50625,0.50625,0.50625
mammographic,0.821058,0.5,0.508265,0.785918,0.789227,0.793966,-,0.785918,0.788359,0.79307

In [35]:
frnn_results = pd.read_csv(Path.cwd() / 'frnn_results.csv', header=None, index_col=0)

In [36]:
for data_set in df.index.values:
    df.loc[data_set, 'frnn'] = frnn_results.loc[data_set, 1]

In [16]:
df.loc['mean'] = df.mean(axis='rows')

/var/folders/_f/yf3dkr5x1397v4ntwhncxfhw0000gn/T/ipykernel_14380/2126629616.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.loc['mean'] = df.mean(axis='rows')

In [17]:
df

,naive-bayes,qr-single,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa
australian,0.777763,0.504006,0.865348,0.856859,0.860529,0.863444,0.863735,0.858174,0.860529,0.863444
cleveland,0.327258,0.212451,0.208347,0.286954,0.289811,0.282134,0.208347,0.286954,0.289811,0.286134
glass,0.487282,0.175556,0.31381,0.255853,0.283234,0.286607,0.273512,0.255853,0.267262,0.256944
heart,0.849167,0.568333,0.785833,0.785,0.786667,0.790833,0.785833,0.789167,0.786667,0.786667
ionosphere,0.861631,0.5,0.658974,0.651282,0.651282,0.651282,0.655449,0.651282,0.651282,0.651282
pima,0.722447,0.487682,0.502775,0.504698,0.502775,0.502775,0.502775,0.504698,0.504627,0.502775
wine,0.975198,0.333333,0.915873,0.796825,0.793175,0.806508,0.730952,0.796825,0.792063,0.792063
bupa,0.572695,0.5,0.5,0.4975,0.4975,0.5,0.5,0.4975,0.4975,0.5
saheart,0.671337,0.503958,0.5,0.501458,0.498333,0.498333,0.5,0.501458,0.501458,0.501458
wisconsin,0.963272,0.525556,0.933215,0.950417,0.954584,0.952501,0.952001,0.948334,0.958751,0.959912
crx,0.67995,0.5,0.501797,0.505741,0.507473,0.505688,0.501797,0.505741,0.505688,0.505688
ecoli,0.413704,0.17381,0.17585,0.247619,0.17381,0.17381,0.17381,0.247619,0.17381,0.17381
haberman,0.572527,0.5,0.5,0.50625,0.50625,0.50625,0.503706,0.50625,0.50625,0.50625
mammographic,0.821058,0.5,0.508265,0.785918,0.789227,0.793966,-,0.785918,0.788359,0.79307
mean,0.692521,0.427478,0.562149,0.580884,0.578189,0.579581,NaN,0.581127,0.577433,0.577107

In [24]:
rule_df = pd.DataFrame(index=data_sets, columns=rules.keys())
for model, rule_dict in rules.items():
    for data_set, rule_count in rule_dict.items():
        rule_df.loc[data_set, model] = rule_count

In [25]:
rule_df

,qr-single,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa
australian,732.2,732.2,426.4,606.5,636.3,529.2,400.6,602.7,631.3
cleveland,331.1,331.1,201.1,266.4,268.2,331.1,199.2,265.3,266.4
glass,225.7,225.7,191.8,193.4,193.6,162.0,191.8,189.1,188.8
heart,303.7,303.7,149.1,239.9,241.0,303.7,144.1,239.1,239.2
ionosphere,460.5,460.5,282.7,291.8,295.9,215.3,282.7,275.4,272.6
pima,824.6,824.6,691.2,692.2,691.9,586.1,691.2,688.6,688.9
wine,211.2,211.2,160.2,162.4,162.0,127.4,160.2,158.3,158.6
bupa,332.4,332.4,307.1,310.9,311.3,280.3,307.1,303.3,302.9
saheart,467.6,467.6,415.8,417.8,418.0,363.9,415.8,414.7,414.6
wisconsin,280.5,280.5,312.6,321.9,347.9,101.3,302.6,298.3,289.2
crx,622.4,622.4,586.9,589.7,591.0,546.6,586.9,584.1,582.8
ecoli,315.0,315.0,302.4,308.2,308.2,287.3,302.4,296.6,296.6
haberman,116.9,116.9,256.9,256.3,256.3,87.2,256.9,256.3,256.3
mammographic,48.3,48.3,466.1,469.5,467.6,0.0,466.0,441.1,440.7